# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=500, verbose_name='Issue Number')),
                ('issue_title', models.CharField(max_length=1000, verbose_name='Issue Title')),
                ('issue_cover', models.ImageField(upload_to='comic_issues', verbose_name='Issue cover')),
                ('issue_description', models.TextField(verbose_name='Description')),
                ('issue_file', models.FileField(help_text='File in pdf or as single image', upload_to='comic_issues_files', verbose_name='Issue file')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Comic Issue',
                'verbose_name_plural': 'Comic Issues',
            },
        ),
        migrations.CreateModel(
            name='ComicSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Series Title')),
                ('cover', models.ImageField(upload_to='comic_series', verbose_name='Series cover')),
                ('description', models.TextField(verbose_name='Description')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist(s)')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comic Series',
                'verbose_name_plural': 'Comic Series',
            },
        ),
        migrations.AddField(
            model_name='comicissue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.ComicSeries', verbose_name='Series Title'),
        ),
    ]
