# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicseries',
            name='artist',
            field=models.CharField(max_length=500, verbose_name='Artist(s)'),
        ),
    ]
