# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comicseries_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicseries',
            name='slug',
        ),
    ]
