# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_remove_comicseries_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicseries',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
