# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comics', '0006_comicissue_issue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicissue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by: '),
        ),
        migrations.AddField(
            model_name='comicseries',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by: '),
        ),
    ]
