# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_auto_20170925_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.FileField(upload_to='panels')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.ComicIssue')),
            ],
            options={
                'verbose_name': 'IssuePanel',
                'verbose_name_plural': 'IssuePanels',
            },
        ),
    ]
