# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_issuepanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicissue',
            name='issue_file',
            field=models.FileField(blank=True, help_text='File in pdf or as single image', null=True, upload_to='comic_issues_files', verbose_name='Issue file'),
        ),
    ]
