# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_auto_20171008_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepanel',
            name='panel',
            field=models.FileField(upload_to='comic_issues_files/panels/'),
        ),
    ]
