# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs', verbose_name='Image'),
        ),
    ]
