# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photography', verbose_name='Image')),
                ('caption', models.TextField(verbose_name='Caption/Description')),
                ('photographer', models.CharField(max_length=500, verbose_name='Photographer')),
                ('studio', models.CharField(default='No studio', help_text='Optional', max_length=500, null=True, verbose_name='Studio')),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photos',
            },
        ),
    ]
